In [2]:
import requests
import os
import pandas as pd
import json
from cred import credentials
import numpy as np

from request_api import get_genesis_api

In [3]:
df_building_completions= get_genesis_api('31121-0002', [2008])
df_building_completions

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Buildings / reconstruction projects,Buildings,Volume constructed,Construction projects,Useful floor space,Dwellings,Living floor space of dwellings,...,Buildings,Volume constructed,Construction projects,Useful floor space,Dwellings,Living floor space of dwellings,Other housing units,Living floor space of other housing units,Rooms,Estimated costs of the construction
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,number,number,1000 cbm,number,1000 qm,number,1000 qm,...,number.2,1000 cbm.2,number.2,1000 qm.2,number.2,1000 qm.2,number.2,1000 qm.2,number.2,Tsd. EUR.2
0,Baden-Württemberg,Residential and non-residential buildings,2008,28663,-,-,-,6231,27587,3346,...,-,-,11296,744,2804,469,-421,-8,15266,1963624
1,Baden-Württemberg,Residential buildings,2008,20935,-,-,-,1008,26854,3269,...,-,-,7793,-94,2693,452,-275,-5,15113,707630
2,Baden-Württemberg,Residential buildings with 1 dwelling,2008,x,x,x,x,x,x,x,...,-,-,x,x,x,x,x,x,x,x
3,Baden-Württemberg,Residential buildings with 2 dwellings,2008,x,x,x,x,x,x,x,...,-,-,x,x,x,x,x,x,x,x
4,Baden-Württemberg,Residential buildings with 1 or 2 dwellings,2008,x,x,x,x,x,x,x,...,-,-,x,x,x,x,x,x,x,x
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,Thüringen,Households as builders of non-res. buildings,2008,395,-,-,-,38,55,5,...,-,-,178,5,46,4,-,-,160,16325
556,Thüringen,Non-profit inst. as builders of non-res. build...,2008,66,-,-,-,44,6,0,...,-,-,35,5,6,0,-15,0,-18,13964
557,Thüringen,"Pub.builders,non-prof.inst.as build.of non-res.b.",2008,235,-,-,-,98,14,0,...,-,-,138,9,14,0,-15,0,-8,94055
558,Thüringen,Non-public builders of non-residential buildings,2008,1147,-,-,-,675,117,10,...,-,-,456,99,66,6,-,-,229,96985
559,Thüringen,Selected infrastr. buildings (non-res. buildings),2008,244,-,-,-,124,10,0,...,-,-,142,9,10,0,-15,0,-3,76657

In [4]:
df_building_completions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 36 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   (Unnamed: 0_level_0, Unnamed: 0_level_1)                560 non-null    object
 1   (Unnamed: 1_level_0, Unnamed: 1_level_1)                560 non-null    object
 2   (Unnamed: 2_level_0, Unnamed: 2_level_1)                560 non-null    int64
 3   (Buildings / reconstruction projects, number)           560 non-null    object
 4   (Buildings, number)                                     560 non-null    object
 5   (Volume constructed, 1000 cbm)                          560 non-null    object
 6   (Construction projects, number)                         560 non-null    object
 7   (Useful floor space, 1000 qm)                           560 non-null    object
 8   (Dwellings, number)                                     560 non-null    object
 9   (Living floor space of dwellings, 1000 qm)              560 non-null    object
 10  (Other housing units, number)                           560 non-null    object
 11  (Living floor space of other housing units, 1000 qm)    560 non-null    object
 12  (Rooms, number)                                         560 non-null    object
 13  (Estimated costs of the construction, Tsd. EUR)         560 non-null    object
 14  (Buildings / reconstruction projects, number.1)         560 non-null    object
 15  (Buildings, number.1)                                   560 non-null    object
 16  (Volume constructed, 1000 cbm.1)                        560 non-null    object
 17  (Construction projects, number.1)                       560 non-null    object
 18  (Useful floor space, 1000 qm.1)                         560 non-null    object
 19  (Dwellings, number.1)                                   560 non-null    object
 20  (Living floor space of dwellings, 1000 qm.1)            560 non-null    object
 21  (Other housing units, number.1)                         560 non-null    object
 22  (Living floor space of other housing units, 1000 qm.1)  560 non-null    object
 23  (Rooms, number.1)                                       560 non-null    object
 24  (Estimated costs of the construction, Tsd. EUR.1)       560 non-null    object
 25  (Buildings / reconstruction projects, number.2)         560 non-null    object
 26  (Buildings, number.2)                                   560 non-null    object
 27  (Volume constructed, 1000 cbm.2)                        560 non-null    object
 28  (Construction projects, number.2)                       560 non-null    object
 29  (Useful floor space, 1000 qm.2)                         560 non-null    object
 30  (Dwellings, number.2)                                   560 non-null    object
 31  (Living floor space of dwellings, 1000 qm.2)            560 non-null    object
 32  (Other housing units, number.2)                         560 non-null    object
 33  (Living floor space of other housing units, 1000 qm.2)  560 non-null    object
 34  (Rooms, number.2)                                       560 non-null    object
 35  (Estimated costs of the construction, Tsd. EUR.2)       560 non-null    object
dtypes: int64(1), object(35)
memory usage: 157.6+ KB