In [50]:
import requests
import pandas as pd
import json
from cred import credentials
from request_api import get_genesis_api

In [52]:
df_population_kreise = pd.read_csv('data/12411-0017.csv', delimiter= ';', skiprows= 5, skipfooter=4, encoding= 'latin1', engine='python', converters={'Unnamed: 1': lambda x: str(x)})
df_population_kreise

,Unnamed: 0,Unnamed: 1,Unnamed: 2,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,...,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt
0,31.12.2000,01001,"Flensburg, kreisfreie Stadt",2339,2442,3288,4363,2364,1967,6194,...,7239,6427,5532,5149,5084,5030,5952,7472,7372,84281
1,31.12.2000,01002,"Kiel, kreisfreie Stadt",6214,5846,8171,10181,5385,4421,16239,...,22623,21377,17356,14545,13473,13896,15016,19026,19471,232612
2,31.12.2000,01003,"Lübeck, kreisfreie Stadt",5900,5889,7965,10142,5572,4312,12348,...,17794,17236,14644,13055,13002,13536,15951,21380,20593,213399
3,31.12.2000,01004,"Neumünster, kreisfreie Stadt",2527,2436,3505,4606,2353,1767,4439,...,6350,6514,5476,4886,4828,5145,5889,7516,6738,79831
4,31.12.2000,01051,"Dithmarschen, Landkreis",4320,4682,6340,8237,4504,3108,6822,...,10763,10725,9733,8711,8341,8118,10429,13698,11153,137174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,31.12.2020,16073,"Saalfeld-Rudolstadt, Landkreis",2161,2504,3398,3942,2362,1517,3323,...,5615,5952,5773,5802,7665,9557,9092,14619,16076,102139
9992,31.12.2020,16074,Saale-Holzland-Kreis,1850,2254,3085,3585,2066,1414,2928,...,4641,5318,5119,4859,6445,7671,7002,11280,11032,82816
9993,31.12.2020,16075,Saale-Orla-Kreis,1756,2041,2760,3392,1907,1248,2748,...,4322,4825,4692,4718,6111,7463,7148,11253,10897,79632
9994,31.12.2020,16076,"Greiz, Landkreis",1985,2352,3239,3956,2345,1416,2865,...,4828,5411,5551,5360,7466,9262,8949,14251,15180,96668
9995,31.12.2020,16077,"Altenburger Land, Landkreis",1759,2068,2793,3510,2105,1325,2677,...,4566,4869,4804,5087,7006,8109,7545,13237,14574,88356

In [53]:
df_population_kreise['Unnamed: 2'].nunique()

476

In [54]:
df_population_kreise.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'key', 'Unnamed: 2': 'kreis'}, inplace=True)
df_population_kreise

,date,key,kreis,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,...,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt
0,31.12.2000,01001,"Flensburg, kreisfreie Stadt",2339,2442,3288,4363,2364,1967,6194,...,7239,6427,5532,5149,5084,5030,5952,7472,7372,84281
1,31.12.2000,01002,"Kiel, kreisfreie Stadt",6214,5846,8171,10181,5385,4421,16239,...,22623,21377,17356,14545,13473,13896,15016,19026,19471,232612
2,31.12.2000,01003,"Lübeck, kreisfreie Stadt",5900,5889,7965,10142,5572,4312,12348,...,17794,17236,14644,13055,13002,13536,15951,21380,20593,213399
3,31.12.2000,01004,"Neumünster, kreisfreie Stadt",2527,2436,3505,4606,2353,1767,4439,...,6350,6514,5476,4886,4828,5145,5889,7516,6738,79831
4,31.12.2000,01051,"Dithmarschen, Landkreis",4320,4682,6340,8237,4504,3108,6822,...,10763,10725,9733,8711,8341,8118,10429,13698,11153,137174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,31.12.2020,16073,"Saalfeld-Rudolstadt, Landkreis",2161,2504,3398,3942,2362,1517,3323,...,5615,5952,5773,5802,7665,9557,9092,14619,16076,102139
9992,31.12.2020,16074,Saale-Holzland-Kreis,1850,2254,3085,3585,2066,1414,2928,...,4641,5318,5119,4859,6445,7671,7002,11280,11032,82816
9993,31.12.2020,16075,Saale-Orla-Kreis,1756,2041,2760,3392,1907,1248,2748,...,4322,4825,4692,4718,6111,7463,7148,11253,10897,79632
9994,31.12.2020,16076,"Greiz, Landkreis",1985,2352,3239,3956,2345,1416,2865,...,4828,5411,5551,5360,7466,9262,8949,14251,15180,96668
9995,31.12.2020,16077,"Altenburger Land, Landkreis",1759,2068,2793,3510,2105,1325,2677,...,4566,4869,4804,5087,7006,8109,7545,13237,14574,88356

In [55]:
df_population_kreise.head(30)

,date,key,kreis,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,...,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt
0,31.12.2000,01001,"Flensburg, kreisfreie Stadt",2339,2442,3288,4363,2364,1967,6194,...,7239,6427,5532,5149,5084,5030,5952,7472,7372,84281
1,31.12.2000,01002,"Kiel, kreisfreie Stadt",6214,5846,8171,10181,5385,4421,16239,...,22623,21377,17356,14545,13473,13896,15016,19026,19471,232612
2,31.12.2000,01003,"Lübeck, kreisfreie Stadt",5900,5889,7965,10142,5572,4312,12348,...,17794,17236,14644,13055,13002,13536,15951,21380,20593,213399
3,31.12.2000,01004,"Neumünster, kreisfreie Stadt",2527,2436,3505,4606,2353,1767,4439,...,6350,6514,5476,4886,4828,5145,5889,7516,6738,79831
4,31.12.2000,01051,"Dithmarschen, Landkreis",4320,4682,6340,8237,4504,3108,6822,...,10763,10725,9733,8711,8341,8118,10429,13698,11153,137174
5,31.12.2000,01053,"Herzogtum Lauenburg, Landkreis",5604,6047,8439,10709,5490,3704,8307,...,14845,16020,13499,11707,11128,11376,13431,16640,13379,179848
6,31.12.2000,01054,"Nordfriesland, Landkreis",5269,5612,7685,9797,5227,3540,8622,...,13654,13355,11230,10325,9884,9849,12119,15524,12841,164280
7,31.12.2000,01055,"Ostholstein, Landkreis",5237,5793,8323,10781,5847,4188,9621,...,15646,16372,14604,13595,12872,13498,16160,20752,18317,202247
8,31.12.2000,01056,"Pinneberg, Landkreis",8709,9415,12540,15614,8219,5692,13756,...,25225,26614,22242,19282,19193,20252,22680,26707,20111,291609
9,31.12.2000,01057,"Plön, Landkreis",3669,4162,5908,7610,4029,2612,6168,...,12092,11455,9511,8712,8382,8778,10231,11991,9913,132895
10,31.12.2000,01058,"Rendsburg-Eckernförde, Landkreis",8581,9295,12776,15988,8395,5760,13243,...,22570,23158,19869,18124,17304,17400,19991,23619,19176,270110
11,31.12.2000,01059,"Schleswig-Flensburg, Landkreis",6399,6924,9822,12548,6440,4349,9966,...,16378,16613,14253,12475,12146,12154,14849,17641,14257,197754
12,31.12.2000,01060,"Segeberg, Landkreis",7863,8436,11402,14533,7780,5212,12482,...,21824,22620,19166,16960,16829,17200,18597,20703,14831,250112
13,31.12.2000,01061,"Steinburg, Landkreis",4271,4667,6528,8516,4132,2802,6310,...,11763,12074,10087,8529,8281,8434,10127,12097,10192,136027
14,31.12.2000,01062,"Stormarn, Landkreis",6619,7140,9408,11505,6196,4237,9833,...,17794,19328,16393,15230,15116,15888,17124,19850,15407,217582
15,31.12.2000,02000,"Hamburg, kreisfreie Stadt",47237,46022,60785,77744,44418,33287,102935,...,165154,157604,125954,105606,105183,109419,116264,151861,137817,1715392
16,31.12.2000,03101,"Braunschweig, kreisfreie Stadt",6193,6065,8601,11003,6298,4921,15265,...,21876,20605,17783,15448,14538,15368,17589,23778,22779,245816
17,31.12.2000,03102,"Salzgitter, kreisfreie Stadt",3281,3433,4835,6209,3453,2508,5941,...,8348,8943,8176,7694,6997,7094,8370,12100,8889,112302
18,31.12.2000,03103,"Wolfsburg, kreisfreie Stadt",2955,3104,4666,6502,3881,2800,6874,...,8906,9319,9052,8447,7454,7980,9967,13874,9261,121805
19,31.12.2000,03151,"Gifhorn, Landkreis",5824,6289,9080,11634,6314,4011,8667,...,13881,16038,14349,12045,9761,9263,10878,14467,9745,171501
20,31.12.2000,03152,"Göttingen, Landkreis (bis 31.10.2016)",7509,7871,10671,14123,7858,5842,19612,...,22698,24362,21005,17343,14816,13765,16549,22354,19104,265396
21,31.12.2000,03153,"Goslar, Landkreis",3847,4124,5920,7615,4259,3150,7921,...,11743,12808,10985,9994,9505,9723,12182,17621,16405,156247
22,31.12.2000,03154,"Helmstedt, Landkreis",2656,2952,4372,5973,3160,2179,4898,...,7528,8398,7722,7026,6233,5781,7141,10601,8418,100033
23,31.12.2000,03155,"Northeim, Landkreis",4258,4568,6317,8581,4817,3358,7431,...,11110,12202,11443,10381,9273,8345,11122,16255,13621,151112
24,31.12.2000,03156,"Osterode am Harz, Landkreis (bis 31.10.2016)",2232,2362,3402,4519,2616,1819,3910,...,6183,6269,5939,5639,5584,5366,6480,10047,8696,85451
25,31.12.2000,03157,"Peine, Landkreis",4224,4389,6139,7646,4340,2855,6142,...,11081,11443,10161,9057,8150,7797,9168,12543,9832,132243
26,31.12.2000,03158,"Wolfenbüttel, Landkreis",3795,4177,5687,7120,3812,2538,5906,...,10444,11016,9954,8589,8003,8042,9260,12114,9588,126697
27,31.12.2000,03159,"Göttingen, Landkreis",-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,31.12.2000,03201,"Hannover, kreisfreie Stadt (bis 31.10.2001)",14110,13276,17129,21113,12249,9946,33745,...,47992,46119,38157,32309,30018,30041,33955,47882,46410,515001
29,31.12.2000,03241,"Region Hannover, Landkreis",-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [56]:
cols = df_population_kreise.columns.drop(['date', 'key','kreis'])

df_population_kreise[cols] = pd.to_numeric(df_population_kreise[cols].stack(), errors='coerce').unstack()

In [57]:
#make NaN values to <NA>
#df_population_kreise[cols] = df_population_kreise[cols].astype('Int64')

#make NaN values to -1

df_population_kreise[cols] = df_population_kreise[cols].fillna(-1).astype(int)

In [58]:
df_population_kreise.head(30)

,date,key,kreis,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,...,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt
0,31.12.2000,01001,"Flensburg, kreisfreie Stadt",2339,2442,3288,4363,2364,1967,6194,...,7239,6427,5532,5149,5084,5030,5952,7472,7372,84281
1,31.12.2000,01002,"Kiel, kreisfreie Stadt",6214,5846,8171,10181,5385,4421,16239,...,22623,21377,17356,14545,13473,13896,15016,19026,19471,232612
2,31.12.2000,01003,"Lübeck, kreisfreie Stadt",5900,5889,7965,10142,5572,4312,12348,...,17794,17236,14644,13055,13002,13536,15951,21380,20593,213399
3,31.12.2000,01004,"Neumünster, kreisfreie Stadt",2527,2436,3505,4606,2353,1767,4439,...,6350,6514,5476,4886,4828,5145,5889,7516,6738,79831
4,31.12.2000,01051,"Dithmarschen, Landkreis",4320,4682,6340,8237,4504,3108,6822,...,10763,10725,9733,8711,8341,8118,10429,13698,11153,137174
5,31.12.2000,01053,"Herzogtum Lauenburg, Landkreis",5604,6047,8439,10709,5490,3704,8307,...,14845,16020,13499,11707,11128,11376,13431,16640,13379,179848
6,31.12.2000,01054,"Nordfriesland, Landkreis",5269,5612,7685,9797,5227,3540,8622,...,13654,13355,11230,10325,9884,9849,12119,15524,12841,164280
7,31.12.2000,01055,"Ostholstein, Landkreis",5237,5793,8323,10781,5847,4188,9621,...,15646,16372,14604,13595,12872,13498,16160,20752,18317,202247
8,31.12.2000,01056,"Pinneberg, Landkreis",8709,9415,12540,15614,8219,5692,13756,...,25225,26614,22242,19282,19193,20252,22680,26707,20111,291609
9,31.12.2000,01057,"Plön, Landkreis",3669,4162,5908,7610,4029,2612,6168,...,12092,11455,9511,8712,8382,8778,10231,11991,9913,132895
10,31.12.2000,01058,"Rendsburg-Eckernförde, Landkreis",8581,9295,12776,15988,8395,5760,13243,...,22570,23158,19869,18124,17304,17400,19991,23619,19176,270110
11,31.12.2000,01059,"Schleswig-Flensburg, Landkreis",6399,6924,9822,12548,6440,4349,9966,...,16378,16613,14253,12475,12146,12154,14849,17641,14257,197754
12,31.12.2000,01060,"Segeberg, Landkreis",7863,8436,11402,14533,7780,5212,12482,...,21824,22620,19166,16960,16829,17200,18597,20703,14831,250112
13,31.12.2000,01061,"Steinburg, Landkreis",4271,4667,6528,8516,4132,2802,6310,...,11763,12074,10087,8529,8281,8434,10127,12097,10192,136027
14,31.12.2000,01062,"Stormarn, Landkreis",6619,7140,9408,11505,6196,4237,9833,...,17794,19328,16393,15230,15116,15888,17124,19850,15407,217582
15,31.12.2000,02000,"Hamburg, kreisfreie Stadt",47237,46022,60785,77744,44418,33287,102935,...,165154,157604,125954,105606,105183,109419,116264,151861,137817,1715392
16,31.12.2000,03101,"Braunschweig, kreisfreie Stadt",6193,6065,8601,11003,6298,4921,15265,...,21876,20605,17783,15448,14538,15368,17589,23778,22779,245816
17,31.12.2000,03102,"Salzgitter, kreisfreie Stadt",3281,3433,4835,6209,3453,2508,5941,...,8348,8943,8176,7694,6997,7094,8370,12100,8889,112302
18,31.12.2000,03103,"Wolfsburg, kreisfreie Stadt",2955,3104,4666,6502,3881,2800,6874,...,8906,9319,9052,8447,7454,7980,9967,13874,9261,121805
19,31.12.2000,03151,"Gifhorn, Landkreis",5824,6289,9080,11634,6314,4011,8667,...,13881,16038,14349,12045,9761,9263,10878,14467,9745,171501
20,31.12.2000,03152,"Göttingen, Landkreis (bis 31.10.2016)",7509,7871,10671,14123,7858,5842,19612,...,22698,24362,21005,17343,14816,13765,16549,22354,19104,265396
21,31.12.2000,03153,"Goslar, Landkreis",3847,4124,5920,7615,4259,3150,7921,...,11743,12808,10985,9994,9505,9723,12182,17621,16405,156247
22,31.12.2000,03154,"Helmstedt, Landkreis",2656,2952,4372,5973,3160,2179,4898,...,7528,8398,7722,7026,6233,5781,7141,10601,8418,100033
23,31.12.2000,03155,"Northeim, Landkreis",4258,4568,6317,8581,4817,3358,7431,...,11110,12202,11443,10381,9273,8345,11122,16255,13621,151112
24,31.12.2000,03156,"Osterode am Harz, Landkreis (bis 31.10.2016)",2232,2362,3402,4519,2616,1819,3910,...,6183,6269,5939,5639,5584,5366,6480,10047,8696,85451
25,31.12.2000,03157,"Peine, Landkreis",4224,4389,6139,7646,4340,2855,6142,...,11081,11443,10161,9057,8150,7797,9168,12543,9832,132243
26,31.12.2000,03158,"Wolfenbüttel, Landkreis",3795,4177,5687,7120,3812,2538,5906,...,10444,11016,9954,8589,8003,8042,9260,12114,9588,126697
27,31.12.2000,03159,"Göttingen, Landkreis",-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
28,31.12.2000,03201,"Hannover, kreisfreie Stadt (bis 31.10.2001)",14110,13276,17129,21113,12249,9946,33745,...,47992,46119,38157,32309,30018,30041,33955,47882,46410,515001
29,31.12.2000,03241,"Region Hannover, Landkreis",-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [59]:
#changing date data type to dateime data type
df_population_kreise["date"] = pd.to_datetime(df_population_kreise["date"])

/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2000' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2002' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2006' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2010' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2013' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2014' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2015' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2016' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2017' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2018' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
/Users/deming/opt/anaconda3/envs/nf_base/lib/python3.9/site-packages/pandas/core/tools/datetimes.py:1047: UserWarning: Parsing '31.12.2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)

In [60]:
df_population_kreise['year'] = pd.DatetimeIndex(df_population_kreise['date']).year

In [61]:
df_population_kreise.drop(columns= 'date', inplace=True)

In [62]:
df_population_kreise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9996 entries, 0 to 9995
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   key                    9996 non-null   object
 1   kreis                  9996 non-null   object
 2   unter 3 Jahre          9996 non-null   int64
 3   3 bis unter 6 Jahre    9996 non-null   int64
 4   6 bis unter 10 Jahre   9996 non-null   int64
 5   10 bis unter 15 Jahre  9996 non-null   int64
 6   15 bis unter 18 Jahre  9996 non-null   int64
 7   18 bis unter 20 Jahre  9996 non-null   int64
 8   20 bis unter 25 Jahre  9996 non-null   int64
 9   25 bis unter 30 Jahre  9996 non-null   int64
 10  30 bis unter 35 Jahre  9996 non-null   int64
 11  35 bis unter 40 Jahre  9996 non-null   int64
 12  40 bis unter 45 Jahre  9996 non-null   int64
 13  45 bis unter 50 Jahre  9996 non-null   int64
 14  50 bis unter 55 Jahre  9996 non-null   int64
 15  55 bis unter 60 Jahre  9996 non-null   int64
 16  60 bis unter 65 Jahre  9996 non-null   int64
 17  65 bis unter 75 Jahre  9996 non-null   int64
 18  75 Jahre und mehr      9996 non-null   int64
 19  Insgesamt              9996 non-null   int64
 20  year                   9996 non-null   int64
dtypes: int64(19), object(2)
memory usage: 1.6+ MB

In [63]:
df_population_kreise.head(30)

,key,kreis,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,25 bis unter 30 Jahre,...,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt,year
0,01001,"Flensburg, kreisfreie Stadt",2339,2442,3288,4363,2364,1967,6194,6067,...,6427,5532,5149,5084,5030,5952,7472,7372,84281,2000
1,01002,"Kiel, kreisfreie Stadt",6214,5846,8171,10181,5385,4421,16239,19372,...,21377,17356,14545,13473,13896,15016,19026,19471,232612,2000
2,01003,"Lübeck, kreisfreie Stadt",5900,5889,7965,10142,5572,4312,12348,14080,...,17236,14644,13055,13002,13536,15951,21380,20593,213399,2000
3,01004,"Neumünster, kreisfreie Stadt",2527,2436,3505,4606,2353,1767,4439,4856,...,6514,5476,4886,4828,5145,5889,7516,6738,79831,2000
4,01051,"Dithmarschen, Landkreis",4320,4682,6340,8237,4504,3108,6822,7490,...,10725,9733,8711,8341,8118,10429,13698,11153,137174,2000
5,01053,"Herzogtum Lauenburg, Landkreis",5604,6047,8439,10709,5490,3704,8307,9523,...,16020,13499,11707,11128,11376,13431,16640,13379,179848,2000
6,01054,"Nordfriesland, Landkreis",5269,5612,7685,9797,5227,3540,8622,9747,...,13355,11230,10325,9884,9849,12119,15524,12841,164280,2000
7,01055,"Ostholstein, Landkreis",5237,5793,8323,10781,5847,4188,9621,10641,...,16372,14604,13595,12872,13498,16160,20752,18317,202247,2000
8,01056,"Pinneberg, Landkreis",8709,9415,12540,15614,8219,5692,13756,15358,...,26614,22242,19282,19193,20252,22680,26707,20111,291609,2000
9,01057,"Plön, Landkreis",3669,4162,5908,7610,4029,2612,6168,7672,...,11455,9511,8712,8382,8778,10231,11991,9913,132895,2000
10,01058,"Rendsburg-Eckernförde, Landkreis",8581,9295,12776,15988,8395,5760,13243,14861,...,23158,19869,18124,17304,17400,19991,23619,19176,270110,2000
11,01059,"Schleswig-Flensburg, Landkreis",6399,6924,9822,12548,6440,4349,9966,10540,...,16613,14253,12475,12146,12154,14849,17641,14257,197754,2000
12,01060,"Segeberg, Landkreis",7863,8436,11402,14533,7780,5212,12482,13674,...,22620,19166,16960,16829,17200,18597,20703,14831,250112,2000
13,01061,"Steinburg, Landkreis",4271,4667,6528,8516,4132,2802,6310,7217,...,12074,10087,8529,8281,8434,10127,12097,10192,136027,2000
14,01062,"Stormarn, Landkreis",6619,7140,9408,11505,6196,4237,9833,10514,...,19328,16393,15230,15116,15888,17124,19850,15407,217582,2000
15,02000,"Hamburg, kreisfreie Stadt",47237,46022,60785,77744,44418,33287,102935,128102,...,157604,125954,105606,105183,109419,116264,151861,137817,1715392,2000
16,03101,"Braunschweig, kreisfreie Stadt",6193,6065,8601,11003,6298,4921,15265,17706,...,20605,17783,15448,14538,15368,17589,23778,22779,245816,2000
17,03102,"Salzgitter, kreisfreie Stadt",3281,3433,4835,6209,3453,2508,5941,6031,...,8943,8176,7694,6997,7094,8370,12100,8889,112302,2000
18,03103,"Wolfsburg, kreisfreie Stadt",2955,3104,4666,6502,3881,2800,6874,6763,...,9319,9052,8447,7454,7980,9967,13874,9261,121805,2000
19,03151,"Gifhorn, Landkreis",5824,6289,9080,11634,6314,4011,8667,9255,...,16038,14349,12045,9761,9263,10878,14467,9745,171501,2000
20,03152,"Göttingen, Landkreis (bis 31.10.2016)",7509,7871,10671,14123,7858,5842,19612,19914,...,24362,21005,17343,14816,13765,16549,22354,19104,265396,2000
21,03153,"Goslar, Landkreis",3847,4124,5920,7615,4259,3150,7921,8445,...,12808,10985,9994,9505,9723,12182,17621,16405,156247,2000
22,03154,"Helmstedt, Landkreis",2656,2952,4372,5973,3160,2179,4898,4995,...,8398,7722,7026,6233,5781,7141,10601,8418,100033,2000
23,03155,"Northeim, Landkreis",4258,4568,6317,8581,4817,3358,7431,8030,...,12202,11443,10381,9273,8345,11122,16255,13621,151112,2000
24,03156,"Osterode am Harz, Landkreis (bis 31.10.2016)",2232,2362,3402,4519,2616,1819,3910,4388,...,6269,5939,5639,5584,5366,6480,10047,8696,85451,2000
25,03157,"Peine, Landkreis",4224,4389,6139,7646,4340,2855,6142,7276,...,11443,10161,9057,8150,7797,9168,12543,9832,132243,2000
26,03158,"Wolfenbüttel, Landkreis",3795,4177,5687,7120,3812,2538,5906,6652,...,11016,9954,8589,8003,8042,9260,12114,9588,126697,2000
27,03159,"Göttingen, Landkreis",-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,2000
28,03201,"Hannover, kreisfreie Stadt (bis 31.10.2001)",14110,13276,17129,21113,12249,9946,33745,40550,...,46119,38157,32309,30018,30041,33955,47882,46410,515001,2000
29,03241,"Region Hannover, Landkreis",-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,2000

In [64]:
cols = list(df_population_kreise.columns.values)
cols

['key',
 'kreis',
 'unter 3 Jahre',
 '3 bis unter 6 Jahre',
 '6 bis unter 10 Jahre',
 '10 bis unter 15 Jahre',
 '15 bis unter 18 Jahre',
 '18 bis unter 20 Jahre',
 '20 bis unter 25 Jahre',
 '25 bis unter 30 Jahre',
 '30 bis unter 35 Jahre',
 '35 bis unter 40 Jahre',
 '40 bis unter 45 Jahre',
 '45 bis unter 50 Jahre',
 '50 bis unter 55 Jahre',
 '55 bis unter 60 Jahre',
 '60 bis unter 65 Jahre',
 '65 bis unter 75 Jahre',
 '75 Jahre und mehr',
 'Insgesamt',
 'year']

In [65]:
df_population_kreise = df_population_kreise[['key',
 'kreis', 'year',
 'unter 3 Jahre',
 '3 bis unter 6 Jahre',
 '6 bis unter 10 Jahre',
 '10 bis unter 15 Jahre',
 '15 bis unter 18 Jahre',
 '18 bis unter 20 Jahre',
 '20 bis unter 25 Jahre',
 '25 bis unter 30 Jahre',
 '30 bis unter 35 Jahre',
 '35 bis unter 40 Jahre',
 '40 bis unter 45 Jahre',
 '45 bis unter 50 Jahre',
 '50 bis unter 55 Jahre',
 '55 bis unter 60 Jahre',
 '60 bis unter 65 Jahre',
 '65 bis unter 75 Jahre',
 '75 Jahre und mehr',
 'Insgesamt']]

In [66]:
df_population_kreise

,key,kreis,year,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,...,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr,Insgesamt
0,01001,"Flensburg, kreisfreie Stadt",2000,2339,2442,3288,4363,2364,1967,6194,...,7239,6427,5532,5149,5084,5030,5952,7472,7372,84281
1,01002,"Kiel, kreisfreie Stadt",2000,6214,5846,8171,10181,5385,4421,16239,...,22623,21377,17356,14545,13473,13896,15016,19026,19471,232612
2,01003,"Lübeck, kreisfreie Stadt",2000,5900,5889,7965,10142,5572,4312,12348,...,17794,17236,14644,13055,13002,13536,15951,21380,20593,213399
3,01004,"Neumünster, kreisfreie Stadt",2000,2527,2436,3505,4606,2353,1767,4439,...,6350,6514,5476,4886,4828,5145,5889,7516,6738,79831
4,01051,"Dithmarschen, Landkreis",2000,4320,4682,6340,8237,4504,3108,6822,...,10763,10725,9733,8711,8341,8118,10429,13698,11153,137174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,16073,"Saalfeld-Rudolstadt, Landkreis",2020,2161,2504,3398,3942,2362,1517,3323,...,5615,5952,5773,5802,7665,9557,9092,14619,16076,102139
9992,16074,Saale-Holzland-Kreis,2020,1850,2254,3085,3585,2066,1414,2928,...,4641,5318,5119,4859,6445,7671,7002,11280,11032,82816
9993,16075,Saale-Orla-Kreis,2020,1756,2041,2760,3392,1907,1248,2748,...,4322,4825,4692,4718,6111,7463,7148,11253,10897,79632
9994,16076,"Greiz, Landkreis",2020,1985,2352,3239,3956,2345,1416,2865,...,4828,5411,5551,5360,7466,9262,8949,14251,15180,96668
9995,16077,"Altenburger Land, Landkreis",2020,1759,2068,2793,3510,2105,1325,2677,...,4566,4869,4804,5087,7006,8109,7545,13237,14574,88356

In [67]:
#get rid of Insgesamt column
df_population_kreise.drop(columns= 'Insgesamt', inplace=True)
df_population_kreise

/var/folders/fd/_0xbkxwj241865ky1839k13m0000gn/T/ipykernel_76889/1791306611.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_population_kreise.drop(columns= 'Insgesamt', inplace=True)

,key,kreis,year,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,25 bis unter 30 Jahre,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr
0,01001,"Flensburg, kreisfreie Stadt",2000,2339,2442,3288,4363,2364,1967,6194,6067,7239,6427,5532,5149,5084,5030,5952,7472,7372
1,01002,"Kiel, kreisfreie Stadt",2000,6214,5846,8171,10181,5385,4421,16239,19372,22623,21377,17356,14545,13473,13896,15016,19026,19471
2,01003,"Lübeck, kreisfreie Stadt",2000,5900,5889,7965,10142,5572,4312,12348,14080,17794,17236,14644,13055,13002,13536,15951,21380,20593
3,01004,"Neumünster, kreisfreie Stadt",2000,2527,2436,3505,4606,2353,1767,4439,4856,6350,6514,5476,4886,4828,5145,5889,7516,6738
4,01051,"Dithmarschen, Landkreis",2000,4320,4682,6340,8237,4504,3108,6822,7490,10763,10725,9733,8711,8341,8118,10429,13698,11153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,16073,"Saalfeld-Rudolstadt, Landkreis",2020,2161,2504,3398,3942,2362,1517,3323,2781,5615,5952,5773,5802,7665,9557,9092,14619,16076
9992,16074,Saale-Holzland-Kreis,2020,1850,2254,3085,3585,2066,1414,2928,2267,4641,5318,5119,4859,6445,7671,7002,11280,11032
9993,16075,Saale-Orla-Kreis,2020,1756,2041,2760,3392,1907,1248,2748,2351,4322,4825,4692,4718,6111,7463,7148,11253,10897
9994,16076,"Greiz, Landkreis",2020,1985,2352,3239,3956,2345,1416,2865,2252,4828,5411,5551,5360,7466,9262,8949,14251,15180
9995,16077,"Altenburger Land, Landkreis",2020,1759,2068,2793,3510,2105,1325,2677,2322,4566,4869,4804,5087,7006,8109,7545,13237,14574

In [68]:
df_population_kreise.to_csv('data/cleaned_population_kreise_2000_2020.csv')

In [69]:
df_population_kreise.head()

,key,kreis,year,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,25 bis unter 30 Jahre,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr
0,01001,"Flensburg, kreisfreie Stadt",2000,2339,2442,3288,4363,2364,1967,6194,6067,7239,6427,5532,5149,5084,5030,5952,7472,7372
1,01002,"Kiel, kreisfreie Stadt",2000,6214,5846,8171,10181,5385,4421,16239,19372,22623,21377,17356,14545,13473,13896,15016,19026,19471
2,01003,"Lübeck, kreisfreie Stadt",2000,5900,5889,7965,10142,5572,4312,12348,14080,17794,17236,14644,13055,13002,13536,15951,21380,20593
3,01004,"Neumünster, kreisfreie Stadt",2000,2527,2436,3505,4606,2353,1767,4439,4856,6350,6514,5476,4886,4828,5145,5889,7516,6738
4,01051,"Dithmarschen, Landkreis",2000,4320,4682,6340,8237,4504,3108,6822,7490,10763,10725,9733,8711,8341,8118,10429,13698,11153

In [88]:
df_population_kreise.replace(to_replace=r'Landkreis$', value='LK', regex=True, inplace=True)
df_population_kreise

/var/folders/fd/_0xbkxwj241865ky1839k13m0000gn/T/ipykernel_76889/2674477908.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_population_kreise.replace(to_replace=r'Landkreis$', value='LK', regex=True, inplace=True)

,key,kreis,year,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,25 bis unter 30 Jahre,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr
0,01001,"Flensburg, kreisfreie Stadt",2000,2339,2442,3288,4363,2364,1967,6194,6067,7239,6427,5532,5149,5084,5030,5952,7472,7372
1,01002,"Kiel, kreisfreie Stadt",2000,6214,5846,8171,10181,5385,4421,16239,19372,22623,21377,17356,14545,13473,13896,15016,19026,19471
2,01003,"Lübeck, kreisfreie Stadt",2000,5900,5889,7965,10142,5572,4312,12348,14080,17794,17236,14644,13055,13002,13536,15951,21380,20593
3,01004,"Neumünster, kreisfreie Stadt",2000,2527,2436,3505,4606,2353,1767,4439,4856,6350,6514,5476,4886,4828,5145,5889,7516,6738
4,01051,"Dithmarschen, LK",2000,4320,4682,6340,8237,4504,3108,6822,7490,10763,10725,9733,8711,8341,8118,10429,13698,11153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,16073,"Saalfeld-Rudolstadt, LK",2020,2161,2504,3398,3942,2362,1517,3323,2781,5615,5952,5773,5802,7665,9557,9092,14619,16076
9992,16074,Saale-Holzland-Kreis,2020,1850,2254,3085,3585,2066,1414,2928,2267,4641,5318,5119,4859,6445,7671,7002,11280,11032
9993,16075,Saale-Orla-Kreis,2020,1756,2041,2760,3392,1907,1248,2748,2351,4322,4825,4692,4718,6111,7463,7148,11253,10897
9994,16076,"Greiz, LK",2020,1985,2352,3239,3956,2345,1416,2865,2252,4828,5411,5551,5360,7466,9262,8949,14251,15180
9995,16077,"Altenburger Land, LK",2020,1759,2068,2793,3510,2105,1325,2677,2322,4566,4869,4804,5087,7006,8109,7545,13237,14574

In [90]:
df_population_kreise.replace(to_replace=r'kreisfreie Stadt$', value='SK', regex=True, inplace=True)
df_population_kreise

/var/folders/fd/_0xbkxwj241865ky1839k13m0000gn/T/ipykernel_76889/1208658739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_population_kreise.replace(to_replace=r'kreisfreie Stadt$', value='SK', regex=True, inplace=True)

,key,kreis,year,unter 3 Jahre,3 bis unter 6 Jahre,6 bis unter 10 Jahre,10 bis unter 15 Jahre,15 bis unter 18 Jahre,18 bis unter 20 Jahre,20 bis unter 25 Jahre,25 bis unter 30 Jahre,30 bis unter 35 Jahre,35 bis unter 40 Jahre,40 bis unter 45 Jahre,45 bis unter 50 Jahre,50 bis unter 55 Jahre,55 bis unter 60 Jahre,60 bis unter 65 Jahre,65 bis unter 75 Jahre,75 Jahre und mehr
0,01001,"Flensburg, SK",2000,2339,2442,3288,4363,2364,1967,6194,6067,7239,6427,5532,5149,5084,5030,5952,7472,7372
1,01002,"Kiel, SK",2000,6214,5846,8171,10181,5385,4421,16239,19372,22623,21377,17356,14545,13473,13896,15016,19026,19471
2,01003,"Lübeck, SK",2000,5900,5889,7965,10142,5572,4312,12348,14080,17794,17236,14644,13055,13002,13536,15951,21380,20593
3,01004,"Neumünster, SK",2000,2527,2436,3505,4606,2353,1767,4439,4856,6350,6514,5476,4886,4828,5145,5889,7516,6738
4,01051,"Dithmarschen, LK",2000,4320,4682,6340,8237,4504,3108,6822,7490,10763,10725,9733,8711,8341,8118,10429,13698,11153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,16073,"Saalfeld-Rudolstadt, LK",2020,2161,2504,3398,3942,2362,1517,3323,2781,5615,5952,5773,5802,7665,9557,9092,14619,16076
9992,16074,Saale-Holzland-Kreis,2020,1850,2254,3085,3585,2066,1414,2928,2267,4641,5318,5119,4859,6445,7671,7002,11280,11032
9993,16075,Saale-Orla-Kreis,2020,1756,2041,2760,3392,1907,1248,2748,2351,4322,4825,4692,4718,6111,7463,7148,11253,10897
9994,16076,"Greiz, LK",2020,1985,2352,3239,3956,2345,1416,2865,2252,4828,5411,5551,5360,7466,9262,8949,14251,15180
9995,16077,"Altenburger Land, LK",2020,1759,2068,2793,3510,2105,1325,2677,2322,4566,4869,4804,5087,7006,8109,7545,13237,14574

In [92]:
df_population_kreise.to_csv('data/formatted_population_kreise.csv')

In [ ]:
#take strings from user
str1 = input("Please Enter First String : ")
str2 =input("Please Enter Second String : ")

x=str1[0:2]

str1=str1.replace(str1[0:2],str2[0:2])

str2=str2.replace(str2[0:2],x)

print("Your first string has become :- ",str1)
print("Your second string has become :- ",str2)