In [1]:
import requests
import os
import pandas as pd
import json
from cred import credentials
import numpy as np

from request_api import get_genesis_api

In [5]:
df_museum = pd.read_csv('data/21611-0102.csv', delimiter= ';', skiprows=3, skipfooter=4, encoding = 'latin1', engine='python')
df_museum

,Unnamed: 0,Unnamed: 1,Unnamed: 2,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Baden-Württemberg,Museen,Anzahl,830,825,821,819,784,784,756,...,791,809,816,779,781,828,794,859,868,841
1,Baden-Württemberg,Ausstellungen,Anzahl,1119,1091,1079,1098,1061,1116,1135,...,1266,1250,1195,1206,1252,1249,1196,1275,1234,1218
2,Baden-Württemberg,Museumsbesuche,1000,14110,12990,13600,13711,14005,14297,13709,...,14448,14548,15032,15307,15288,15680,15660,16006,15882,15207
3,Bayern,Museen,Anzahl,867,876,868,889,837,816,849,...,913,900,889,881,885,741,757,782,755,590
4,Bayern,Ausstellungen,Anzahl,1335,1311,1253,1294,1327,1318,1325,...,1309,1396,1401,1339,1382,1179,1216,1269,1244,1208
5,Bayern,Museumsbesuche,1000,20454,18779,19348,18663,18477,18706,18233,...,20312,20395,19833,19970,20290,20235,18919,19514,19659,18523
6,Berlin,Museen,Anzahl,128,128,125,121,117,124,126,...,135,138,134,143,143,145,136,146,144,147
7,Berlin,Ausstellungen,Anzahl,347,343,389,352,397,404,391,...,436,400,375,382,358,379,368,364,378,391
8,Berlin,Museumsbesuche,1000,8666,9317,11292,10907,12009,13981,13396,...,14971,15791,15931,16168,16204,16321,16456,15798,16694,17251
9,Brandenburg,Museen,Anzahl,265,265,263,263,258,239,249,...,234,245,246,239,240,245,236,228,235,225
10,Brandenburg,Ausstellungen,Anzahl,535,501,511,528,471,496,523,...,476,484,476,472,496,478,411,439,458,415
11,Brandenburg,Museumsbesuche,1000,3316,3592,3472,3546,3281,3368,3511,...,3287,3345,3800,3389,3715,3814,3667,4088,3788,4118
12,Bremen,Museen,Anzahl,23,22,25,22,22,24,28,...,26,26,30,28,29,31,29,29,29,27
13,Bremen,Ausstellungen,Anzahl,52,84,68,78,77,71,61,...,59,70,93,98,101,83,81,82,101,85
14,Bremen,Museumsbesuche,1000,1599,1449,1398,1383,1530,1481,1599,...,1224,1244,1270,1111,1079,1541,1538,1593,1545,1597
15,Hamburg,Museen,Anzahl,49,47,45,47,40,42,46,...,41,42,46,46,50,55,51,47,47,40
16,Hamburg,Ausstellungen,Anzahl,146,158,120,142,111,108,93,...,70,92,99,105,121,110,76,79,93,67
17,Hamburg,Museumsbesuche,1000,2090,1821,2140,2083,2226,2205,2290,...,1871,1699,1873,2258,2161,2408,2431,2292,2178,1924
18,Hessen,Museen,Anzahl,327,333,333,324,324,324,320,...,316,319,328,309,338,330,301,302,313,304
19,Hessen,Ausstellungen,Anzahl,632,682,718,720,688,668,661,...,656,662,675,635,667,638,593,593,644,568
20,Hessen,Museumsbesuche,1000,4807,5043,4898,4701,4596,4776,4805,...,4782,4641,6039,4861,4976,5277,5130,6021,5491,6220
21,Mecklenburg-Vorpommern,Museen,Anzahl,151,171,179,166,167,170,169,...,158,162,172,163,159,160,156,157,155,146
22,Mecklenburg-Vorpommern,Ausstellungen,Anzahl,343,389,372,370,365,378,308,...,321,324,322,328,290,294,277,293,278,264
23,Mecklenburg-Vorpommern,Museumsbesuche,1000,3200,3325,3273,3094,2880,3172,3561,...,3528,3470,3207,3040,3144,3258,3230,3203,2840,2923
24,Niedersachsen,Museen,Anzahl,513,508,497,501,500,501,501,...,497,487,474,479,482,556,499,510,513,492
25,Niedersachsen,Ausstellungen,Anzahl,874,810,808,913,916,861,870,...,876,800,804,815,769,811,779,827,862,749
26,Niedersachsen,Museumsbesuche,1000,7524,7098,7037,6717,6729,6816,6717,...,6410,6589,6322,6397,6693,7095,6869,6877,6635,6380
27,Nordrhein-Westfalen,Museen,Anzahl,530,542,528,516,529,510,532,...,512,519,524,513,535,562,510,537,551,557
28,Nordrhein-Westfalen,Ausstellungen,Anzahl,1269,1283,1255,1358,1202,1215,1266,...,1187,1176,1163,1230,1244,1322,1136,1257,1203,1089
29,Nordrhein-Westfalen,Museumsbesuche,1000,14275,13450,14711,14767,15492,15559,14556,...,16350,15176,15954,15184,15185,15474,14926,15441,14589,15144
30,Rheinland-Pfalz,Museen,Anzahl,283,289,283,288,271,287,295,...,286,279,278,256,271,313,325,311,316,291
31,Rheinland-Pfalz,Ausstellungen,Anzahl,448,398,388,370,383,373,387,...,396,434,376,365,394,434,461,409,394,385
32,Rheinland-Pfalz,Museumsbesuche,1000,4106,4229,4041,3766,3797,4631,3960,...,3770,3927,4536,4385,4555,4595,4848,4525,4210,3824
33,Saarland,Museen,Anzahl,46,53,44,41,43,45,42,...,48,50,49,52,50,56,53,53,51,55
34,Saarland,Ausstellungen,Anzahl,82,88,95,116,104,109,88,...,92,96,102,108,96,93,100,79,77,76
35,Saarland,Museumsbesuche,1000,463,580,617,670,703,754,619,...,816,773,618,728,710,609,600,686,566,745
36,Sachsen,Museen,Anzahl,326,315,320,308,326,320,315,...,325,316,328,323,328,334,315,322,332,305
37,Sachsen,Ausstellungen,Anzahl,835,782,819,843,910,879,911,...,859,825,811,781,793,816,781,730,754,760
38,Sachsen,Museumsbesuche,1000,7051,7319,7659,7795,7785,8131,8222,...,8142,8653,9134,8777,8791,8521,8051,8353,8396,8418
39,Sachsen-Anhalt,Museen,Anzahl,188,195,189,180,173,175,183,...,174,178,178,176,194,188,173,186,184,165
40,Sachsen-Anhalt,Ausstellungen,Anzahl,439,454,394,392,422,412,362,...,388,386,383,363,384,356,330,337,329,303
41,Sachsen-Anhalt,Museumsbesuche,1000,2464,2493,2658,2649,2667,2510,2811,...,2402,2616,2809,2511,2638,2698,2620,2923,2594,2255
42,Schleswig-Holstein,Museen,Anzahl,180,174,174,177,173,174,174,...,180,183,176,161,170,175,155,166,176,169
43,Schleswig-Holstein,Ausstellungen,Anzahl,356,353,348,327,302,342,325,...,346,333,275,278,288,328,282,303,314,274
44,Schleswig-Holstein,Museumsbesuche,1000,2922,2793,2793,2651,2568,2698,2684,...,2601,2590,2474,2279,2400,2554,2454,2632,2600,2640
45,Thüringen,Museen,Anzahl,186,186,184,185,183,177,191,...,187,182,180,187,191,213,209,196,196,189
46,Thüringen,Ausstellungen,Anzahl,461,495,425,463,462,485,439,...,435,452,390,437,423,455,459,429,387,403
47,Thüringen,Museumsbesuche,1000,4173,4084,4296,4306,3900,4219,4177,...,4282,4124,3975,4062,4157,4344,4477,4424,3995,4465

In [7]:
df_museum.rename(columns={'Unnamed: 0':'bundesland', 'Unnamed: 1': 'subject', 'Unnamed: 2': 'unit'}, inplace=True)
df_museum

,bundesland,subject,unit,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Baden-Württemberg,Museen,Anzahl,830,825,821,819,784,784,756,...,791,809,816,779,781,828,794,859,868,841
1,Baden-Württemberg,Ausstellungen,Anzahl,1119,1091,1079,1098,1061,1116,1135,...,1266,1250,1195,1206,1252,1249,1196,1275,1234,1218
2,Baden-Württemberg,Museumsbesuche,1000,14110,12990,13600,13711,14005,14297,13709,...,14448,14548,15032,15307,15288,15680,15660,16006,15882,15207
3,Bayern,Museen,Anzahl,867,876,868,889,837,816,849,...,913,900,889,881,885,741,757,782,755,590
4,Bayern,Ausstellungen,Anzahl,1335,1311,1253,1294,1327,1318,1325,...,1309,1396,1401,1339,1382,1179,1216,1269,1244,1208
5,Bayern,Museumsbesuche,1000,20454,18779,19348,18663,18477,18706,18233,...,20312,20395,19833,19970,20290,20235,18919,19514,19659,18523
6,Berlin,Museen,Anzahl,128,128,125,121,117,124,126,...,135,138,134,143,143,145,136,146,144,147
7,Berlin,Ausstellungen,Anzahl,347,343,389,352,397,404,391,...,436,400,375,382,358,379,368,364,378,391
8,Berlin,Museumsbesuche,1000,8666,9317,11292,10907,12009,13981,13396,...,14971,15791,15931,16168,16204,16321,16456,15798,16694,17251
9,Brandenburg,Museen,Anzahl,265,265,263,263,258,239,249,...,234,245,246,239,240,245,236,228,235,225
10,Brandenburg,Ausstellungen,Anzahl,535,501,511,528,471,496,523,...,476,484,476,472,496,478,411,439,458,415
11,Brandenburg,Museumsbesuche,1000,3316,3592,3472,3546,3281,3368,3511,...,3287,3345,3800,3389,3715,3814,3667,4088,3788,4118
12,Bremen,Museen,Anzahl,23,22,25,22,22,24,28,...,26,26,30,28,29,31,29,29,29,27
13,Bremen,Ausstellungen,Anzahl,52,84,68,78,77,71,61,...,59,70,93,98,101,83,81,82,101,85
14,Bremen,Museumsbesuche,1000,1599,1449,1398,1383,1530,1481,1599,...,1224,1244,1270,1111,1079,1541,1538,1593,1545,1597
15,Hamburg,Museen,Anzahl,49,47,45,47,40,42,46,...,41,42,46,46,50,55,51,47,47,40
16,Hamburg,Ausstellungen,Anzahl,146,158,120,142,111,108,93,...,70,92,99,105,121,110,76,79,93,67
17,Hamburg,Museumsbesuche,1000,2090,1821,2140,2083,2226,2205,2290,...,1871,1699,1873,2258,2161,2408,2431,2292,2178,1924
18,Hessen,Museen,Anzahl,327,333,333,324,324,324,320,...,316,319,328,309,338,330,301,302,313,304
19,Hessen,Ausstellungen,Anzahl,632,682,718,720,688,668,661,...,656,662,675,635,667,638,593,593,644,568
20,Hessen,Museumsbesuche,1000,4807,5043,4898,4701,4596,4776,4805,...,4782,4641,6039,4861,4976,5277,5130,6021,5491,6220
21,Mecklenburg-Vorpommern,Museen,Anzahl,151,171,179,166,167,170,169,...,158,162,172,163,159,160,156,157,155,146
22,Mecklenburg-Vorpommern,Ausstellungen,Anzahl,343,389,372,370,365,378,308,...,321,324,322,328,290,294,277,293,278,264
23,Mecklenburg-Vorpommern,Museumsbesuche,1000,3200,3325,3273,3094,2880,3172,3561,...,3528,3470,3207,3040,3144,3258,3230,3203,2840,2923
24,Niedersachsen,Museen,Anzahl,513,508,497,501,500,501,501,...,497,487,474,479,482,556,499,510,513,492
25,Niedersachsen,Ausstellungen,Anzahl,874,810,808,913,916,861,870,...,876,800,804,815,769,811,779,827,862,749
26,Niedersachsen,Museumsbesuche,1000,7524,7098,7037,6717,6729,6816,6717,...,6410,6589,6322,6397,6693,7095,6869,6877,6635,6380
27,Nordrhein-Westfalen,Museen,Anzahl,530,542,528,516,529,510,532,...,512,519,524,513,535,562,510,537,551,557
28,Nordrhein-Westfalen,Ausstellungen,Anzahl,1269,1283,1255,1358,1202,1215,1266,...,1187,1176,1163,1230,1244,1322,1136,1257,1203,1089
29,Nordrhein-Westfalen,Museumsbesuche,1000,14275,13450,14711,14767,15492,15559,14556,...,16350,15176,15954,15184,15185,15474,14926,15441,14589,15144
30,Rheinland-Pfalz,Museen,Anzahl,283,289,283,288,271,287,295,...,286,279,278,256,271,313,325,311,316,291
31,Rheinland-Pfalz,Ausstellungen,Anzahl,448,398,388,370,383,373,387,...,396,434,376,365,394,434,461,409,394,385
32,Rheinland-Pfalz,Museumsbesuche,1000,4106,4229,4041,3766,3797,4631,3960,...,3770,3927,4536,4385,4555,4595,4848,4525,4210,3824
33,Saarland,Museen,Anzahl,46,53,44,41,43,45,42,...,48,50,49,52,50,56,53,53,51,55
34,Saarland,Ausstellungen,Anzahl,82,88,95,116,104,109,88,...,92,96,102,108,96,93,100,79,77,76
35,Saarland,Museumsbesuche,1000,463,580,617,670,703,754,619,...,816,773,618,728,710,609,600,686,566,745
36,Sachsen,Museen,Anzahl,326,315,320,308,326,320,315,...,325,316,328,323,328,334,315,322,332,305
37,Sachsen,Ausstellungen,Anzahl,835,782,819,843,910,879,911,...,859,825,811,781,793,816,781,730,754,760
38,Sachsen,Museumsbesuche,1000,7051,7319,7659,7795,7785,8131,8222,...,8142,8653,9134,8777,8791,8521,8051,8353,8396,8418
39,Sachsen-Anhalt,Museen,Anzahl,188,195,189,180,173,175,183,...,174,178,178,176,194,188,173,186,184,165
40,Sachsen-Anhalt,Ausstellungen,Anzahl,439,454,394,392,422,412,362,...,388,386,383,363,384,356,330,337,329,303
41,Sachsen-Anhalt,Museumsbesuche,1000,2464,2493,2658,2649,2667,2510,2811,...,2402,2616,2809,2511,2638,2698,2620,2923,2594,2255
42,Schleswig-Holstein,Museen,Anzahl,180,174,174,177,173,174,174,...,180,183,176,161,170,175,155,166,176,169
43,Schleswig-Holstein,Ausstellungen,Anzahl,356,353,348,327,302,342,325,...,346,333,275,278,288,328,282,303,314,274
44,Schleswig-Holstein,Museumsbesuche,1000,2922,2793,2793,2651,2568,2698,2684,...,2601,2590,2474,2279,2400,2554,2454,2632,2600,2640
45,Thüringen,Museen,Anzahl,186,186,184,185,183,177,191,...,187,182,180,187,191,213,209,196,196,189
46,Thüringen,Ausstellungen,Anzahl,461,495,425,463,462,485,439,...,435,452,390,437,423,455,459,429,387,403
47,Thüringen,Museumsbesuche,1000,4173,4084,4296,4306,3900,4219,4177,...,4282,4124,3975,4062,4157,4344,4477,4424,3995,4465

In [12]:
df_museum.bundesland.unique()

array(['Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen',
       'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen',
       'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen',
       'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen'], dtype=object)

In [8]:
df_museum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bundesland  48 non-null     object
 1   subject     48 non-null     object
 2   unit        48 non-null     object
 3   2002        48 non-null     int64
 4   2003        48 non-null     int64
 5   2004        48 non-null     int64
 6   2005        48 non-null     int64
 7   2006        48 non-null     int64
 8   2007        48 non-null     int64
 9   2008        48 non-null     int64
 10  2009        48 non-null     int64
 11  2010        48 non-null     int64
 12  2011        48 non-null     int64
 13  2012        48 non-null     int64
 14  2013        48 non-null     int64
 15  2014        48 non-null     int64
 16  2015        48 non-null     int64
 17  2016        48 non-null     int64
 18  2017        48 non-null     int64
 19  2018        48 non-null     int64
 20  2019        48 non-null     int64
dtypes: int64(18), object(3)
memory usage: 8.0+ KB

In [10]:
df_museum.to_csv('data/cleaned_museum.csv')