In [1]:
import requests
import pandas as pd
import json
from cred import credentials
from request_api import get_genesis_api

In [2]:
df_genehmigung = pd.read_csv('data/31111-0003.csv', delimiter=';', skiprows=6, skipfooter=4, header=[1,2], encoding = 'latin1')
df_genehmigung

/var/folders/fd/_0xbkxwj241865ky1839k13m0000gn/T/ipykernel_55282/2995926883.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df_genehmigung = pd.read_csv('data/31111-0003.csv', delimiter=';', skiprows=6, skipfooter=4, header=[1,2], encoding = 'latin1')

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Gebäude/Baumaßnahmen,Gebäude,Rauminhalt,Baumaßnahmen,Nutzfläche,Wohnungen,Wohnfläche der Wohnungen,Sonstige Wohneinheiten,Wohnfläche der sonstigen Wohneinheiten,Wohnräume,Veranschlagte Kosten des Bauwerks
,Unnamed: 0_level_1,Unnamed: 1_level_1,Unnamed: 2_level_1,Anzahl,Anzahl,1000 cbm,Anzahl,1000 qm,Anzahl,1000 qm,Anzahl,1000 qm,Anzahl,Tsd. EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,-,-,-,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,-,-,-,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,-,-,-,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,-,-,-,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,-,-,-,6233,35145,4141,-,-,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,-,-,-,766,275,16,-,-,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,-,-,-,600,228,17,-,-,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,-,-,-,597,235,16,-,-,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,-,-,-,691,158,9,-,-,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,-,-,-,829,86,6,-,-,141,1125840

In [3]:
df_genehmigung.columns = df_genehmigung.columns.map('_'.join)
df_genehmigung

,Unnamed: 0_level_0_Unnamed: 0_level_1,Unnamed: 1_level_0_Unnamed: 1_level_1,Unnamed: 2_level_0_Unnamed: 2_level_1,Gebäude/Baumaßnahmen_Anzahl,Gebäude_Anzahl,Rauminhalt_1000 cbm,Baumaßnahmen_Anzahl,Nutzfläche_1000 qm,Wohnungen_Anzahl,Wohnfläche der Wohnungen_1000 qm,Sonstige Wohneinheiten_Anzahl,Wohnfläche der sonstigen Wohneinheiten_1000 qm,Wohnräume_Anzahl,Veranschlagte Kosten des Bauwerks_Tsd. EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,-,-,-,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,-,-,-,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,-,-,-,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,-,-,-,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,-,-,-,6233,35145,4141,-,-,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,-,-,-,766,275,16,-,-,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,-,-,-,600,228,17,-,-,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,-,-,-,597,235,16,-,-,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,-,-,-,691,158,9,-,-,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,-,-,-,829,86,6,-,-,141,1125840

In [4]:
df_genehmigung.columns = df_genehmigung.columns.str.replace(' ', '_')
df_genehmigung

,Unnamed:_0_level_0_Unnamed:_0_level_1,Unnamed:_1_level_0_Unnamed:_1_level_1,Unnamed:_2_level_0_Unnamed:_2_level_1,Gebäude/Baumaßnahmen_Anzahl,Gebäude_Anzahl,Rauminhalt_1000_cbm,Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,-,-,-,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,-,-,-,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,-,-,-,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,-,-,-,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,-,-,-,6233,35145,4141,-,-,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,-,-,-,766,275,16,-,-,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,-,-,-,600,228,17,-,-,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,-,-,-,597,235,16,-,-,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,-,-,-,691,158,9,-,-,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,-,-,-,829,86,6,-,-,141,1125840

In [5]:
df_genehmigung.rename(columns={'Unnamed:_0_level_0_Unnamed:_0_level_1': 'bundesland', 'Unnamed:_1_level_0_Unnamed:_1_level_1': 'building_type', 'Unnamed:_2_level_0_Unnamed:_2_level_1': 'year'}, inplace=True)
df_genehmigung

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Gebäude_Anzahl,Rauminhalt_1000_cbm,Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,-,-,-,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,-,-,-,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,-,-,-,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,-,-,-,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,-,-,-,6233,35145,4141,-,-,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,-,-,-,766,275,16,-,-,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,-,-,-,600,228,17,-,-,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,-,-,-,597,235,16,-,-,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,-,-,-,691,158,9,-,-,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,-,-,-,829,86,6,-,-,141,1125840

In [6]:
df_genehmigung.drop(columns=['Gebäude_Anzahl', 'Rauminhalt_1000_cbm', 'Baumaßnahmen_Anzahl'], inplace=True)
df_genehmigung

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,6233,35145,4141,-,-,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,766,275,16,-,-,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,600,228,17,-,-,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,597,235,16,-,-,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,691,158,9,-,-,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,829,86,6,-,-,141,1125840

In [ ]:
df_genehmigung.info()

In [7]:
cols = df_genehmigung.columns.drop(['bundesland', 'building_type', 'year'])

df_genehmigung[cols] = df_genehmigung[cols].apply(pd.to_numeric, errors='coerce')
df_genehmigung

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,7088,26110,3205,598.0,21.0,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,5304,26635,3232,662.0,20.0,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,5439,28842,3515,364.0,16.0,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,6314,34343,4110,149.0,9.0,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,6233,35145,4141,NaN,NaN,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,766,275,16,NaN,NaN,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,600,228,17,NaN,NaN,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,597,235,16,NaN,NaN,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,691,158,9,NaN,NaN,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,829,86,6,NaN,NaN,141,1125840

In [ ]:
df_genehmigung.info()

In [ ]:
cols = df_genehmigung.columns.drop(['bundesland', 'building_type', 'year'])
cols

In [8]:
df_genehmigung[cols] = df_genehmigung[cols].fillna(-1).astype(int)
df_genehmigung

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
0,Baden-Württemberg,Wohn- und Nichtwohngebäude,2008,28299,7088,26110,3205,598,21,129170,9886140
1,Baden-Württemberg,Wohn- und Nichtwohngebäude,2009,27488,5304,26635,3232,662,20,128893,9652859
2,Baden-Württemberg,Wohn- und Nichtwohngebäude,2010,28989,5439,28842,3515,364,16,139906,9384899
3,Baden-Württemberg,Wohn- und Nichtwohngebäude,2011,31684,6314,34343,4110,149,9,160133,11274441
4,Baden-Württemberg,Wohn- und Nichtwohngebäude,2012,30429,6233,35145,4141,-1,-1,159950,11564838
...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,766,275,16,-1,-1,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,600,228,17,-1,-1,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,597,235,16,-1,-1,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,691,158,9,-1,-1,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,829,86,6,-1,-1,141,1125840

In [9]:
df_genehmigung_wohngebäude_nichtwohngebäude = df_genehmigung.query('building_type == "Wohn- und Nichtwohngebäude"')

In [17]:
df_genehmigung_nichtwohngebäude_wohngebäude = df_genehmigung.query('building_type == "Nichtwohngebäude" or building_type == "Wohngebäude"')
df_genehmigung_nichtwohngebäude_wohngebäude

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Nutzfläche_1000_qm,Wohnungen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Sonstige_Wohneinheiten_Anzahl,Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm,Wohnräume_Anzahl,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
14,Baden-Württemberg,Wohngebäude,2008,20181,902,25248,3110,622,21,125979,4362991
15,Baden-Württemberg,Wohngebäude,2009,20243,935,26017,3163,544,18,126624,4690118
16,Baden-Württemberg,Wohngebäude,2010,21441,1005,28037,3429,452,16,137168,5139286
17,Baden-Württemberg,Wohngebäude,2011,23868,1211,32923,3980,126,9,155733,6087801
18,Baden-Württemberg,Wohngebäude,2012,23118,1257,34385,4065,-1,-1,157525,6356030
...,...,...,...,...,...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,766,275,16,-1,-1,506,680068
668,Thüringen,Nichtwohngebäude,2018,1324,600,228,17,-1,-1,540,700833
669,Thüringen,Nichtwohngebäude,2019,1367,597,235,16,-1,-1,557,710564
670,Thüringen,Nichtwohngebäude,2020,1259,691,158,9,-1,-1,294,909545
671,Thüringen,Nichtwohngebäude,2021,1423,829,86,6,-1,-1,141,1125840

In [18]:
df_genehmigung_nichtwohngebäude_wohngebäude.columns

Index(['bundesland', 'building_type', 'year', 'Gebäude/Baumaßnahmen_Anzahl',
       'Nutzfläche_1000_qm', 'Wohnungen_Anzahl',
       'Wohnfläche_der_Wohnungen_1000_qm', 'Sonstige_Wohneinheiten_Anzahl',
       'Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm', 'Wohnräume_Anzahl',
       'Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR'],
      dtype='object')

In [20]:
df_genehmigung_nichtwohngebäude_wohngebäude.drop(columns=['Nutzfläche_1000_qm', 'Wohnungen_Anzahl','Sonstige_Wohneinheiten_Anzahl','Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm', 'Wohnräume_Anzahl'], inplace=True)

/var/folders/fd/_0xbkxwj241865ky1839k13m0000gn/T/ipykernel_55282/1567059.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_genehmigung_nichtwohngebäude_wohngebäude.drop(columns=['Nutzfläche_1000_qm', 'Wohnungen_Anzahl','Sonstige_Wohneinheiten_Anzahl','Wohnfläche_der_sonstigen_Wohneinheiten_1000_qm', 'Wohnräume_Anzahl'], inplace=True)

In [21]:
df_genehmigung_nichtwohngebäude_wohngebäude

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
14,Baden-Württemberg,Wohngebäude,2008,20181,3110,4362991
15,Baden-Württemberg,Wohngebäude,2009,20243,3163,4690118
16,Baden-Württemberg,Wohngebäude,2010,21441,3429,5139286
17,Baden-Württemberg,Wohngebäude,2011,23868,3980,6087801
18,Baden-Württemberg,Wohngebäude,2012,23118,4065,6356030
...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,16,680068
668,Thüringen,Nichtwohngebäude,2018,1324,17,700833
669,Thüringen,Nichtwohngebäude,2019,1367,16,710564
670,Thüringen,Nichtwohngebäude,2020,1259,9,909545
671,Thüringen,Nichtwohngebäude,2021,1423,6,1125840

In [22]:
df_genehmigung_wohngebäude = df_genehmigung_nichtwohngebäude_wohngebäude.query('building_type == "Wohngebäude"')
df_genehmigung_wohngebäude

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
14,Baden-Württemberg,Wohngebäude,2008,20181,3110,4362991
15,Baden-Württemberg,Wohngebäude,2009,20243,3163,4690118
16,Baden-Württemberg,Wohngebäude,2010,21441,3429,5139286
17,Baden-Württemberg,Wohngebäude,2011,23868,3980,6087801
18,Baden-Württemberg,Wohngebäude,2012,23118,4065,6356030
...,...,...,...,...,...,...
653,Thüringen,Wohngebäude,2017,3736,560,864708
654,Thüringen,Wohngebäude,2018,3648,669,945045
655,Thüringen,Wohngebäude,2019,3493,566,950926
656,Thüringen,Wohngebäude,2020,3795,633,1153100
657,Thüringen,Wohngebäude,2021,3840,553,1100622

In [23]:
df_genehmigung_nichtwohngebäude = df_genehmigung_nichtwohngebäude_wohngebäude.query('building_type == "Nichtwohngebäude"')
df_genehmigung_nichtwohngebäude

,bundesland,building_type,year,Gebäude/Baumaßnahmen_Anzahl,Wohnfläche_der_Wohnungen_1000_qm,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR
28,Baden-Württemberg,Nichtwohngebäude,2008,8118,95,5523149
29,Baden-Württemberg,Nichtwohngebäude,2009,7245,69,4962741
30,Baden-Württemberg,Nichtwohngebäude,2010,7548,85,4245613
31,Baden-Württemberg,Nichtwohngebäude,2011,7816,130,5186640
32,Baden-Württemberg,Nichtwohngebäude,2012,7311,77,5208808
...,...,...,...,...,...,...
667,Thüringen,Nichtwohngebäude,2017,1354,16,680068
668,Thüringen,Nichtwohngebäude,2018,1324,17,700833
669,Thüringen,Nichtwohngebäude,2019,1367,16,710564
670,Thüringen,Nichtwohngebäude,2020,1259,9,909545
671,Thüringen,Nichtwohngebäude,2021,1423,6,1125840

In [28]:
df_genehmigung_merged = df_genehmigung_wohngebäude.merge(df_genehmigung_nichtwohngebäude, on=['bundesland', 'year'])
df_genehmigung_merged

,bundesland,building_type_x,year,Gebäude/Baumaßnahmen_Anzahl_x,Wohnfläche_der_Wohnungen_1000_qm_x,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_x,building_type_y,Gebäude/Baumaßnahmen_Anzahl_y,Wohnfläche_der_Wohnungen_1000_qm_y,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_y
0,Baden-Württemberg,Wohngebäude,2008,20181,3110,4362991,Nichtwohngebäude,8118,95,5523149
1,Baden-Württemberg,Wohngebäude,2009,20243,3163,4690118,Nichtwohngebäude,7245,69,4962741
2,Baden-Württemberg,Wohngebäude,2010,21441,3429,5139286,Nichtwohngebäude,7548,85,4245613
3,Baden-Württemberg,Wohngebäude,2011,23868,3980,6087801,Nichtwohngebäude,7816,130,5186640
4,Baden-Württemberg,Wohngebäude,2012,23118,4065,6356030,Nichtwohngebäude,7311,77,5208808
...,...,...,...,...,...,...,...,...,...,...
219,Thüringen,Wohngebäude,2017,3736,560,864708,Nichtwohngebäude,1354,16,680068
220,Thüringen,Wohngebäude,2018,3648,669,945045,Nichtwohngebäude,1324,17,700833
221,Thüringen,Wohngebäude,2019,3493,566,950926,Nichtwohngebäude,1367,16,710564
222,Thüringen,Wohngebäude,2020,3795,633,1153100,Nichtwohngebäude,1259,9,909545
223,Thüringen,Wohngebäude,2021,3840,553,1100622,Nichtwohngebäude,1423,6,1125840

In [29]:
df_genehmigung_merged.columns = df_genehmigung_merged.columns.str.replace('x', 'Wohngebäude')

In [30]:
df_genehmigung_merged.columns = df_genehmigung_merged.columns.str.replace('y', 'Nichtwohngebäude')

In [32]:
df_genehmigung_merged.drop(columns=['building_tNichtwohngebäudepe_Wohngebäude', 'building_tNichtwohngebäudepe_Nichtwohngebäude'], inplace=True)
df_genehmigung_merged

,bundesland,Nichtwohngebäudeear,Gebäude/Baumaßnahmen_Anzahl_Wohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Wohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Wohngebäude,Gebäude/Baumaßnahmen_Anzahl_Nichtwohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Nichtwohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Nichtwohngebäude
0,Baden-Württemberg,2008,20181,3110,4362991,8118,95,5523149
1,Baden-Württemberg,2009,20243,3163,4690118,7245,69,4962741
2,Baden-Württemberg,2010,21441,3429,5139286,7548,85,4245613
3,Baden-Württemberg,2011,23868,3980,6087801,7816,130,5186640
4,Baden-Württemberg,2012,23118,4065,6356030,7311,77,5208808
...,...,...,...,...,...,...,...,...
219,Thüringen,2017,3736,560,864708,1354,16,680068
220,Thüringen,2018,3648,669,945045,1324,17,700833
221,Thüringen,2019,3493,566,950926,1367,16,710564
222,Thüringen,2020,3795,633,1153100,1259,9,909545
223,Thüringen,2021,3840,553,1100622,1423,6,1125840

In [33]:
df_genehmigung_merged.rename(columns={'Nichtwohngebäudeear':'year'}, inplace=True)

In [34]:
df_genehmigung_merged.head(20)

,bundesland,year,Gebäude/Baumaßnahmen_Anzahl_Wohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Wohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Wohngebäude,Gebäude/Baumaßnahmen_Anzahl_Nichtwohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Nichtwohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Nichtwohngebäude
0,Baden-Württemberg,2008,20181,3110,4362991,8118,95,5523149
1,Baden-Württemberg,2009,20243,3163,4690118,7245,69,4962741
2,Baden-Württemberg,2010,21441,3429,5139286,7548,85,4245613
3,Baden-Württemberg,2011,23868,3980,6087801,7816,130,5186640
4,Baden-Württemberg,2012,23118,4065,6356030,7311,77,5208808
5,Baden-Württemberg,2013,23315,4179,6704141,7132,109,5647435
6,Baden-Württemberg,2014,22986,4151,6919639,6978,118,6274236
7,Baden-Württemberg,2015,23728,4383,7546000,6774,104,6323644
8,Baden-Württemberg,2016,25061,4963,8641357,7919,120,7160845
9,Baden-Württemberg,2017,23885,4597,8402089,7022,120,7142421
10,Baden-Württemberg,2018,23622,4669,8888119,7200,106,7836863
11,Baden-Württemberg,2019,24318,4620,9558667,7313,136,8989753
12,Baden-Württemberg,2020,26600,5139,10696829,6849,118,8265768
13,Baden-Württemberg,2021,28221,5451,12051562,6788,150,9139891
14,Bayern,2008,25024,4084,6222185,12023,46,6726975
15,Bayern,2009,26418,4276,6708783,12353,52,8117596
16,Bayern,2010,29609,4879,7869984,13607,52,7255319
17,Bayern,2011,33404,5802,9693887,13799,103,8866696
18,Bayern,2012,32562,5775,9784693,12965,82,8607353
19,Bayern,2013,34012,6097,10560850,13226,82,8750454

In [35]:
df_genehmigung_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 224 entries, 0 to 223
Data columns (total 8 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   bundesland                                                   224 non-null    object
 1   year                                                         224 non-null    int64
 2   Gebäude/Baumaßnahmen_Anzahl_Wohngebäude                      224 non-null    int64
 3   Wohnfläche_der_Wohnungen_1000_qm_Wohngebäude                 224 non-null    int64
 4   Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Wohngebäude       224 non-null    int64
 5   Gebäude/Baumaßnahmen_Anzahl_Nichtwohngebäude                 224 non-null    int64
 6   Wohnfläche_der_Wohnungen_1000_qm_Nichtwohngebäude            224 non-null    int64
 7   Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Nichtwohngebäude  224 non-null    int64
dtypes: int64(7), object(1)
memory usage: 15.8+ KB

In [38]:
df_grouped_population = pd.read_csv('data/grouped_population (1).csv', index_col= [0])
df_grouped_population

     year               state    age_avg  total_population
0    2000   Baden-Württemberg  39.681041          10524415
1    2000              Bayern  40.042644          12230255
2    2000              Berlin  40.522362           3382169
3    2000         Brandenburg  40.749223           2601962
4    2000              Bremen  42.060658            660225
..    ...                 ...        ...               ...
811  2050            Saarland  47.602190            822000
812  2050             Sachsen  46.823152           3585000
813  2050      Sachsen-Anhalt  48.502364           1692000
814  2050  Schleswig-Holstein  48.137918           2661000
815  2050           Thüringen  48.540906           1699000

[816 rows x 4 columns]

In [48]:
df_grouped_population.rename(columns={'state':'bundesland'}, inplace=True)

In [53]:
 df_pop_genehmigung = df_grouped_population.merge(df_genehmigung_merged, on=['year','bundesland'], how= 'inner')

In [55]:
df_pop_genehmigung.to_csv('data/cleaned_population_genehmigung.csv')

In [56]:
df_pop_genehmigung.corr()

,year,age_avg,total_population,Gebäude/Baumaßnahmen_Anzahl_Wohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Wohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Wohngebäude,Gebäude/Baumaßnahmen_Anzahl_Nichtwohngebäude,Wohnfläche_der_Wohnungen_1000_qm_Nichtwohngebäude,Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Nichtwohngebäude
year,1.000000,0.218897,0.009846,0.108363,0.189413,0.273606,-0.028331,0.197740,0.161922
age_avg,0.218897,1.000000,-0.377272,-0.317145,-0.369850,-0.341942,-0.329775,-0.350705,-0.371877
total_population,0.009846,-0.377272,1.000000,0.924100,0.913894,0.824040,0.825063,0.799463,0.811153
Gebäude/Baumaßnahmen_Anzahl_Wohngebäude,0.108363,-0.317145,0.924100,1.000000,0.985429,0.943937,0.937827,0.895449,0.923513
Wohnfläche_der_Wohnungen_1000_qm_Wohngebäude,0.189413,-0.369850,0.913894,0.985429,1.000000,0.972988,0.906268,0.913977,0.940320
Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Wohngebäude,0.273606,-0.341942,0.824040,0.943937,0.972988,1.000000,0.876644,0.933826,0.966447
Gebäude/Baumaßnahmen_Anzahl_Nichtwohngebäude,-0.028331,-0.329775,0.825063,0.937827,0.906268,0.876644,1.000000,0.843522,0.922896
Wohnfläche_der_Wohnungen_1000_qm_Nichtwohngebäude,0.197740,-0.350705,0.799463,0.895449,0.913977,0.933826,0.843522,1.000000,0.935580
Veranschlagte_Kosten_des_Bauwerks_Tsd._EUR_Nichtwohngebäude,0.161922,-0.371877,0.811153,0.923513,0.940320,0.966447,0.922896,0.935580,1.000000

In [57]:
df_grouped_population.to_csv('data/cleaned_grouped_population.csv')